### ISSUE TITLE
Return code 3221225501

### ISSUE THREAD

**Issue by riocorre** [ryanvolz/radioconda#10]
Hi,

I have installed GNU Radio 3.9.5.0 on Windows 10. I have a simple configuration of a RTL-SDR sink and QT GUI Sink. 

The error makes end the program with this code:  Return code 3221225501
It also happens with QT GUI Frequency Sink.

It does not happen with QT Time Sink.

Do you have some hints about it?

Thanks!

Enrique

**Comment by ryanvolz** [comment]
Hi Enrique!

I take this to mean that your flowgraph does not run at all, immediately crashing with that error code? Does it say anything else before that happens?

Some searching seems to indicate that that error code is related to being unable to load a DLL. How are you running GNU Radio Companion? (e.g. from the Start Menu entry called "GNU Radio Companion (radioconda)", or by running `gnuradio-companion` from the "Conda Prompt (radioconda)"). It's possible that it can't find a DLL because the conda environment has not been activated properly by running using one of those methods.

**Comment by riocorre** [comment]
Hi Ryan,

thank you for your email.

I have the same error If I run the application from the Start Menu or  by
the Condia Prompt.

I add some images.

[image: image.png]
[image: image.png]
[image: image.png]

[image: image.png]


Thanks!

Enrique

**Comment by ryanvolz** [comment]
Hi Enrique,

The images didn't come through Github's system. I think you'll have to use the website to post them to the issue.

**Comment by riocorre** [comment]
Thank you Ryan,

here you have the images,

Cheers,
![image](https://user-images.githubusercontent.com/99558040/153768094-799f8b71-fb6d-4103-81f9-93df180e33b1.png)
![image (1)](https://user-images.githubusercontent.com/99558040/153768095-59327001-6554-4a8b-8847-5a295a497bec.png)
![image (2)](https://user-images.githubusercontent.com/99558040/153768096-def1e70e-caf6-4772-b283-234e23e6b817.png)
![image (3)](https://user-images.githubusercontent.com/99558040/153768098-23a86169-1549-47b5-bbc3-a3650057caca.png)

Enrique

**Comment by riocorre** [comment]
Hi, Ryan,
 here are the images.
![image](https://user-images.githubusercontent.com/99558040/153841764-e64b95be-84bd-49ec-ae32-329b9fa219ac.png)
![image (1)](https://user-images.githubusercontent.com/99558040/153841766-4eef98d4-312c-4565-a52c-56be342c9eca.png)
![image (2)](https://user-images.githubusercontent.com/99558040/153841771-6adc08c8-b5ee-45ae-a2df-7c5edf7f249b.png)
![image (3)](https://user-images.githubusercontent.com/99558040/153841776-61a070f3-1d2a-4908-af00-f0bf24a82557.png)

**Comment by riocorre** [comment]
Hi Ryan,

I have uploaded the images at Github, did you received them?

Enrique

**Comment by ryanvolz** [comment]
Hi Enrique,

This is a tough one. That error code is not much to go on, and that's the only clue we have besides that fact that it works for the Qt Time sink but not the GUI sink. I tried your exact flowgraph and it worked fine for me, so that doesn't help.

Maybe we can figure out what is different about your system, specifically related to Qt since that seems to be a culprit. Do you have any other versions of GNU Radio installed (e.g. GNCDevelopment, PothosSDR), or have they been installed in the past? Interference with old/other installations has sometimes been a problem. How about Qt being installed somewhere else as well? Any other applications installed that you know use Qt and may have brought and incompatible version? Anything else special about your setup that might be relevant?

Failing progress from that, maybe the next step would be to launch `ipython` from the Conda Prompt and then manually enter the Python script produced by your failing flowgraph line-by-line, until we can see what line causes the segmentation fault.

**Comment by riocorre** [comment]
Thank you Ryan.

It is the first time I installed GNU radio on this computer.

Enrique

**Comment by riocorre** [comment]
Thank you Ryan.

I will let it as is by the moment.

Enrique

**Comment by ryanvolz** [comment]
I think this is better summarized in #25.
