### ISSUE TITLE
Install Location radioconda windows 64-bit 2024.05.29

### ISSUE THREAD

**Issue by AKProwl** [ryanvolz/radioconda#105]
"Error: 'Destination Folder" contains 1 space.
This can cause problems with several conda packages.
Please remove the space from the destination folder."

When i create a blank folder or a blank space in my computers directory it still does not install
[Screenshot 2024-09-07 235102.pdf](https://github.com/user-attachments/files/16919900/Screenshot.2024-09-07.235102.pdf)
![Screenshot 2024-09-07 235102](https://github.com/user-attachments/assets/e3ea2e20-fda4-42fd-8ec1-64af18034d57)

**Comment by ryanvolz** [comment]
Unfortunately this is a conda limitation on Windows that the installation path cannot contain any spaces. The only way it will work is if you pick a destination that does not have spaces in the path name.

See the second answer under the [Installing Anaconda FAQ](https://docs.anaconda.com/working-with-conda/reference/faq/#installing-anaconda), which applies equally well to radioconda since they're built with the same installer software.
