### ISSUE TITLE
global_blocks_path is set to system wide path

### ISSUE THREAD

**Issue by nils-werner** [ryanvolz/radioconda#19]
The Global Blocks Path preference is set to the system wide `/usr/local/share` directory:

```
grc.global_blocks_path = /usr/local/share/gnuradio/grc/blocks
```

I believe it should be set to be inside the environment:

```
$CONDA_PREFIX/share/gnuradio/grc/blocks
```

**Comment by ryanvolz** [comment]
This is one way in which the GNU Radio conda package is patched: it ignores the `global_blocks_path` setting in the config file and looks in its installation prefix. You have that setting because of (presumably) building GNU Radio yourself and installing it into `/usr/local/share`, but someone who has only used the conda package should not have any line like that in their config file. Regardless, conda-gnuradio should ignore it. Are you finding that it isn't? If you need to point to a different block location, you can still use `locak_blocks_path`.

**Comment by nils-werner** [comment]
Ah intersting, `$CONDA_PREFIX/etc/gnuradio/conf.d/grc.conf` indeed does not have that line, but the output of `gnuradio-config-info --prefs` shows that value regardless...
