### ISSUE TITLE
Suggestion: how about gr-ieee802-15 and gr-ieee802-11 or gr-lte

### ISSUE THREAD

**Issue by loidmen** [ryanvolz/radioconda#36]
The wime project with OOT modules for wifi and zigbee, is interesting. Also gr-lte block to help build an  lte receiver.

Thanks.

**Comment by ryanvolz** [comment]
`gnuradio-ieee802_11` and `gnuradio-ieee802_15_4` are now available through the `ryanvolz` conda channel (compatible with `gnuradio` 3.10.7.0) and will be included in radioconda imminently.

gr-lte appears to have not even been ported to GR 3.8 yet, let alone 3.10, so that will have to wait until such time as someone updates it and takes over maintenance.
