### ISSUE TITLE
RuntimeError: SoapySDR::Device::make() no match

### ISSUE THREAD

**Issue by bb1gfd** [ryanvolz/radioconda#70]
I just downloaded and installed radioconda-2023.07.26-Windows-x86_64.exe.
It worked fine until I tried to use Soapy SDRPlay Source grc block.
rsp1aTest1.py test file with only 2 blocks, with extension changed to .txt, is attached
[rsp1aTest1.txt](https://github.com/ryanvolz/radioconda/files/12186828/rsp1aTest1.txt)
Attempt to run it gives the error:
 File "rsp1aTest1.py", line 96, in __init__
    self.soapy_sdrplay_source_0 = soapy.source(dev, "fc32", 1, 'rsp1a',
RuntimeError: SoapySDR::Device::make() no match

**Comment by ryanvolz** [comment]
Yeah, sorry! Despite the existence of the Soapy SDRPlay Source block in GRC, support for SDRPlay devices does not currently come preinstalled with radioconda. This is because the driver is not open source, and me redistributing their binary driver is legally questionable even though they provide it for free. Plus I don't personally have an SDRPlay device to motivate figuring out a good workaround.

One thing you could do is install their binary driver and then build the Soapy SDRPlay module yourself, as described in more detail [here](https://github.com/ryanvolz/radioconda/issues/29#issuecomment-1281214289). Apparently other people have gotten that to work, but I think success will depend on how comfortable you are with compiling software.

I'm tracking the request for SDRPlay support in #41, so I'll close this in favor of keeping that issue active.
